name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file docker/Dockerfile --tag us-east4-docker.pkg.dev/fiery-booth-417309/mmpose/mmpose
    - name: Push the Docker image
      run: docker push us-east4-docker.pkg.dev/fiery-booth-417309/mmpose/mmpose

          
